#!/usr/bin/env bash
# vnstat-dashboard setup script

set -e

echo "╔════════════════════════════════════════════════════════╗"
echo "║         vnstat Dashboard — Setup Interativo           ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

# Check if .env exists
if [ -f .env ]; then
    echo "⚠️  .env já existe. Pulando configuração de variáveis."
    echo ""
else
    echo "📝 Configurando variáveis de ambiente..."
    echo ""

    # Generate secure random strings
    SECRET=$(openssl rand -hex 32)
    JWT_SECRET=$(openssl rand -hex 32)
    COLLECTOR_KEY=$(openssl rand -hex 24)

    # Prompt user inputs
    read -p "Admin username [admin]: " ADMIN_USER
    ADMIN_USER=${ADMIN_USER:-admin}

    read -sp "Admin password: " ADMIN_PASS
    echo ""

    read -p "MySQL root password (deixar em branco = gerada): " MYSQL_ROOT
    MYSQL_ROOT=${MYSQL_ROOT:-$(openssl rand -hex 16)}

    read -p "MySQL vnstat user password (deixar em branco = gerada): " MYSQL_PASS
    MYSQL_PASS=${MYSQL_PASS:-$(openssl rand -hex 16)}

    # Create .env
    cat > .env <<EOF
# Auto-generated by setup.sh
SECRET_KEY=$SECRET
JWT_SECRET_KEY=$JWT_SECRET
COLLECTOR_API_KEY=$COLLECTOR_KEY
ADMIN_USER=$ADMIN_USER
ADMIN_PASS=$ADMIN_PASS
FLASK_ENV=production
MYSQL_ROOT_PASSWORD=$MYSQL_ROOT
MYSQL_PASSWORD=$MYSQL_PASS
DATABASE_URL=mysql+pymysql://vnstat:$MYSQL_PASS@db:3306/vnstat_dash
HOSTS=pi:Raspberry Pi:100.x.x.1,note:Note (Debian):100.x.x.2,ser4ph-arm:Oracle ARM:100.x.x.3
EOF

    echo "✓ .env criado com sucesso"
    echo ""
    echo "Salve estas informações de segurança:"
    echo "  • Collector API Key: $COLLECTOR_KEY"
    echo "  • MySQL root pass:   $MYSQL_ROOT"
    echo "  • MySQL vnstat pass: $MYSQL_PASS"
    echo ""
fi

# Check Docker
if ! command -v docker &> /dev/null; then
    echo "❌ Docker não encontrado. Instale Docker antes de continuar."
    exit 1
fi

echo "🐳 Iniciando containers..."
docker-compose up -d

echo ""
echo "⏳ Aguardando inicialização (30s)..."
sleep 30

# Check if app is running
if docker-compose ps | grep -q "vnstat-app"; then
    echo "✓ Container app está rodando"
else
    echo "❌ Container app não está rodando"
    docker-compose logs app
    exit 1
fi

echo ""
echo "✅ Setup completo!"
echo ""
echo "Próximos passos:"
echo "  1. Acessar: http://localhost"
echo "  2. Fazer login com credenciais configuradas"
echo "  3. Instalar coletores nos hosts:"
echo ""
echo "     cd collector"
echo "     scp -r . pi:/tmp/vnstat-collector-install/"
echo "     ssh pi 'cd /tmp/vnstat-collector-install && sudo bash install-collector.sh pi http://SEU_IP:80 $COLLECTOR_KEY eth0'"
echo ""
echo "  4. Repetir para outros hosts (note, ser4ph-arm)"
echo ""
echo "Logs:"
echo "  • docker-compose logs -f app"
echo "  • docker-compose logs -f db"
echo "  • docker-compose logs -f web"
echo ""
echo "Para parar:"
echo "  • docker-compose down"
echo ""
